services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  web:
    image: nginx:1.26-alpine
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/html
    depends_on:
      - app
    networks:
      - app-network

  db:
    build: ./docker/mysql
    command: --mysql-native-password=ON --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --general_log=1 --log_output=FILE --general_log_file=mysqld.log
    user: 1000:1000
    ports:
      - 3306:3306
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - db-store:/var/lib/mysql
    networks:
      - app-network

volumes:
  db-store:

networks:
  app-network:
    driver: bridge
