version: "3.9"
services:
  app:
    build: ./docker/php
    volumes:
      - ./public:/var/www/html

  web:
    image: nginx:1.26-alpine
    ports:
      - 8080:80
    volumes:
      - ./public:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/html

  db:
    build: ./docker/mysql
    command: --mysql-native-password=ON --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --general_log=1 --log_output=FILE --general_log_file=mysqld.log
    user: 1000:1000
    ports:
      - 3306:3306
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - db-store:/var/lib/mysql

volumes:
  db-store: