name: Quality checks

on:
  pull_request:

jobs:
  php-quality:
    name: PHPUnit, PHPStan and ECS
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Run PHPUnit
        run: composer test

      - name: Run PHPStan
        run: composer stan

      - name: Run ECS
        run: composer ecs
